chore: add GitHub repository integration as prerequisite
getsentry/action-release pull request #80
Opened 2022-03-03 22:10 UTC by gnumoksha

https://github.com/getsentry/action-release/issues/12#issuecomment-663879593

2022-03-04 01:18 UTC, ceorourke commented
Tagging in @mgaeta who is more familiar with the CI on this repo than I am - any idea why the test is failing?

2022-05-09 21:45 UTC, mgaeta requested changes
I have some minor copy changes. The test failures look like a problem on our end. I'll start investigating that now.

2022-05-09 21:45 UTC, mgaeta commented on README.md
> +#### Create a GitHub repository integration
```
#### Install GitHub integration
```

2022-05-09 21:45 UTC, mgaeta commented on README.md
> +For this action to find your commits, your GitHub repository needs to be added. In Sentry, navigate to _Settings > Integrations > GitHub_. Go to the "Configurations" tab and click "Configure". Confir
```
A GitHub repository must be added to Sentry in order for this action to find your commits.
```

2023-02-24 15:24 UTC, closed without merging